### ISSUE TITLE
登入view

### ISSUE THREAD

**Issue by iamcxa** [trunk-studio/RN_TradeMuch#24]
先只有facebook登入方式

**Comment by kyoyadmoon** [comment]
- [ todo 1 ] 

- [ todo 2 ]

**Comment by iamcxa** [comment]
![image](https://cloud.githubusercontent.com/assets/1522808/14009793/69714474-f1ca-11e5-9420-b89585fdd98b.png)

**Comment by FuYaoDe** [comment]
![screenshot 2016-03-25 11 07 30](https://cloud.githubusercontent.com/assets/6357215/14037040/8574a412-f27a-11e5-9bb5-ef1a30f016ab.png)
