### ISSUE TITLE
登入後的使用者可以進行我的留言板功能操作

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/RN_TradeMuch#45]
## 注意事項

使用者需要先行登入
## Demo 步驟
1. 使用者可點選側滑選單，在點選我的留言版（顯示未讀項目數量），進入該功能
2. 在留言板功能中將會看到目前有需要回覆的清單(自己上架的)，每一項目顯示未讀訊息數量
3. 點選進入有需要回覆的清單中，將可以看到留言的訊息
4. 進入對話後，再回到留言清單中，將會看到原本已提示的訊息消失

**Comment by kyoyadmoon** [comment]
https://app.zeplin.io/project.html#pid=56c19c97360c538b0604bf23&sid=570b1db7b390497301e4eae3
https://app.zeplin.io/project.html#pid=56c19c97360c538b0604bf23&sid=570b1dbab390497301e4ebe9
https://app.zeplin.io/project.html#pid=56c19c97360c538b0604bf23&sid=570b1dbbf6b4ff433bf25da5
